source "https://supermarket.getchef.com"

cookbook 'windows', '~> 1.34.6'
cookbook '7-zip', '~> 1.0.2'
cookbook 'chocolatey', '~> 0.2.0'
cookbook 'webpi', '~> 1.2.8'
cookbook 'ms_dotnet45', '~> 1.1.2'
cookbook 'sqlce', '~> 1.0.0'
cookbook 'visualstudio', github: 'pknath19/visualstudio'
cookbook 'minitest-handler', '~> 1.3.2'
cookbook 'chocolatey-installer', github: 'pknath19/chocolatey-installer'
cookbook 'webpi-installer', github: 'pknath19/webpi-installer'